# 存放各项配置

# LLM
# 智谱API
ZHIPU_API_KEY = ""
ZHIPU_BASE_URL = "https://open.bigmodel.cn/api/paas/v4/"
ZHIPU_LLM_MODEL = "glm-4.7-flash"
ZHIPU_VLM_MODEL = "glm-4.6v-flash"

# 硅基流动API
SILICONFLOW_API_KEY = ""
SILICONFLOW_BASE_URL = "https://api.siliconflow.cn/v1"
# SILICONFLOW_LLM_MODEL = "Qwen/Qwen2.5-7B-Instruct"
SILICONFLOW_LLM_MODEL = "deepseek-ai/DeepSeek-V3.2"
SILICONFLOW_VLM_MODEL = "THUDM/GLM-4.1V-9B-Thinking"

# GPT4o API
GPT_API_KEY = ""
GPT_BASE_URL = "https://api.gptsapi.net/v1" 
GPT_LLM_MODEL = "gpt-4o"
GPT_VLM_MODEL = "gpt-4o"

# ollama API
OLLAMA_API_KEY = "ollama"  # 任意字符串即可
OLLAMA_BASE_URL = "http://localhost:11434/v1"
OLLAMA_LLM_MODEL = "deepseek-r1:7b"


TARGET_API_KEY = SILICONFLOW_API_KEY
TARGET_BASE_URL = SILICONFLOW_BASE_URL
TARGET_LLM_MODEL = SILICONFLOW_LLM_MODEL
TARGET_VLM_MODEL = SILICONFLOW_VLM_MODEL
# Planner LLM
TASK_LLM_API_KEY = TARGET_API_KEY
TASK_LLM_BASE_URL = TARGET_BASE_URL
TASK_LLM_MODEL = TARGET_LLM_MODEL

# Judge LLM
JUDGE_LLM_API_KEY = TARGET_API_KEY
JUDGE_LLM_BASE_URL = TARGET_BASE_URL
JUDGE_LLM_MODEL = TARGET_LLM_MODEL

# VLM
VLM_API_KEY = TARGET_API_KEY
VLM_API_BASE_URL = TARGET_BASE_URL
VLM_MODEL = TARGET_VLM_MODEL

MAX_REPLAN_TIMES = 1

# RAG
RAG_MODEL = "sentence-transformers/all-mpnet-base-v2"
RAG_SIMILARITY_THRESHOLD = 0.5
HISTORY_PATH = "memory/rag_history.json"

# JUDGE规则调整 cm
MOVE_ERROR_THRESHOLD = 5.0
PLACE_ERROR_THRESHOLD = 5.0
CATCH_ERROR_THRESHOLD = 20.0

# 物体默认长宽高(cm)
BOX_SIZE = (50, 50, 50)

# YOLO Detect Objects
YOLO_DETECT_OBJECTS = ["desk","chair","bottle","apple","banana"]